### ISSUE TITLE
msvc2015 inflatevalidate Entry Point Not Found  libpng16-16.dll

### ISSUE THREAD

**Issue by zhaokaixs** [libSDL2pp/libSDL2pp#113]
![image](https://user-images.githubusercontent.com/7833585/33535070-66858a5e-d8e6-11e7-89d2-ab32ef81ff3d.png)

**Comment by AMDmi3** [comment]
Could you please describe the problem properly?

**Comment by zhaokaixs** [comment]
I download SDL2_devel-2.0.7-VC.zip ,SDL2_image-devel-2.0.2-VC.zip ,SDL2_ttf-devel-2.0.14-VC.zip,and i build libSDL2pp to run image example, but it report 'inflatevalidate Entry Point Not Found libpng16-16.dll'

**Comment by zhaokaixs** [comment]
![image](https://user-images.githubusercontent.com/7833585/33585591-f566dec6-d99f-11e7-9ad1-76679922b995.png)

**Comment by zhaokaixs** [comment]
I see where the problem is. If I use SDL2_ttf-devel-2.0.14-VC's zlib1.dll, it will happen. SDLImage2.0.2 won't do. What should I do to make it better at the same time?

**Comment by zhaokaixs** [comment]
SDL_image zlib-1.2.11 SDL_TTF zlib1.2.5

**Comment by AMDmi3** [comment]
Doesn't using zlib1.dll from SDL2_image help?

**Comment by zhaokaixs** [comment]
SDL_TTF zlib1.dll version

**Comment by AMDmi3** [comment]
Sorry, I don't understand. Anyway, bundled library incompatibility is SDL problem, I don't think we can solve it in libSDL2pp.

**Comment by Kiritow** [comment]
It's not libSDL2pp or SDL problem. Perhaps according to the PATH configure, there is more than one libpng16-16.dll. And multiple different versions of DLLs might cause this problem.

**Comment by AMDmi3** [comment]
It's SDL problem in a way that SDL2_ttf and SDL2_image bundle different versions of the same library. It's Windows problem mainly though as it allows DLL hell. However, it could still work submitter use letest version of the library. I still haven't understood whether he has tried this.

**Comment by zhaokaixs** [comment]
thanks, i have try
