### ISSUE TITLE
how can i update font texture

### ISSUE THREAD

**Issue by zhaokaixs** [libSDL2pp/libSDL2pp#117]
char sz[128] = {};
		sprintf(sz, "%d", i++);
		Texture su(render, font.RenderUTF8_Blended("test update ", SDL_Color{ 255, 255, 255, 255 }));
		Surface fff = font.RenderUTF8_Blended(sz, SDL_Color{ 255, 255, 255, 255 });
		su.Update(SDL2pp::NullOpt, fff);

if i want to modify words, how to do when update each time?

**Comment by AMDmi3** [comment]
Create a new texture
