### ISSUE TITLE
A big try catch block for the whole program?

### ISSUE THREAD

**Issue by boost2017** [libSDL2pp/libSDL2pp#118]
I was learning SDL2 and it is c based. Then I found this project which is meant to wrap into c++. It is very cool project.

The thing I kind of think is weird is that, by looking at the example, the whole program will then be under a try-catch block.

Maybe we should about it.

**Comment by AMDmi3** [comment]
What's wrong about it? Not handling exceptions on the top level is what would be weird, and more granular exception handling is not needed there at all.

**Comment by ooxi** [comment]
While there is some debate about whether or not a whole program try-catch has more advantages then disadvantages, it's certainly useful for demonstration in examples.

Nevertheless I think a platform like [stackoverflow|https://stackoverflow.com/questions/26704430/try-catch-whole-program] is more suitable for such a discussion :-)
