### ISSUE TITLE
Mingw64 & MSYS2 ; unable to compile libSDL2pp (linking to stdlib failed)

### ISSUE THREAD

**Issue by Aecron** [libSDL2pp/libSDL2pp#122]
Hello,

I've never really used pkg-config nor CMake, so i don't really know what informations would be relevants, feel free to ask me anything you see fit.

I've been trying to compile your SDL2pp library (managed to link the SDL2 library inside the FindSDL2x.cmake files), and the compilation process fails trying to link the stdlib. (hundreds of linker's line "undefined reference/symbol to 'std::string::c_str() const" and such. I've been spending severals hours on internet & looking into all the CMake/Makefiles, and I can't find a way to fix the issue.

Running this from a MSYS2 shell with Mingw64 (x86_64) on a Windows 10 device.
Any advice?
Thanks.

**Comment by AMDmi3** [comment]
See appveyor script, it compiles the library with both msvc and mingw compilers. Unfortunately that's all I can suggest, since I don't use windows myself. Also, could you be compiling with c instead of c++ compiler?

**Comment by Aecron** [comment]
Well, that honestly was my first thought ; but as all the compilation process is done by your CMake/Makefiles, i have no clue why it would be using gcc instead of g++, and have even less idea on where i could change that behaviour, if it was the case. I'll look into the appveyor.
thanks for the quick answer!

**Comment by Aecron** [comment]
Okay, so apparently by feeding to CMake the CXX compiler to use, it solves the issue of stdlib linkage, confirming it was using a C compiler instead.
Had few other issue as i was using a static linking (SDL_image, mixer, ttf & such wouldn't be able to link to SDL_functions), switched to dynamic, and apparently compilation of the library works.
Althought, i had to turn off the compilation of examples, as they were failing to link to libSDLmain.a (make was trying to build it for some reason?)

Thanks for your assistance, your small intervention actually helped me a lot in solving this matter.
