### ISSUE TITLE
Mix_Init: MP3 support not available

### ISSUE THREAD

**Issue by ryancheung** [libSDL2pp/libSDL2pp#123]
Keep raise this in macOS, anyone help?

Code:
```cpp
    int result = 0;
    int flags = MIX_INIT_MP3;

    if (SDL_Init(SDL_INIT_AUDIO) < 0) {
        printf("Failed to init SDL\n");
        exit(1);
    }

    if (flags != (result = Mix_Init(flags))) {
        printf("Could not initialize mixer (result: %d).\n", result);
        printf("Mix_Init: %s\n", Mix_GetError());
        exit(1);
    }
```

**Comment by AMDmi3** [comment]
Please submit SDL problems upstream.

**Comment by ryancheung** [comment]
In case someone has this frustrating problem, go https://github.com/veandco/go-sdl2/issues/299 to get helped.

**Comment by ryancheung** [comment]
For the latest homebrew, run brew install sdl2_mixer --with-mpg123 can fix all these trouble.

**Comment by jdavid5815** [comment]
I can't seen to use that brew option:

Error: invalid option: --with-mpg123

Update brew and made sure that mpg123 was installed .. to no avail.
