### ISSUE TITLE
Malformed build command

### ISSUE THREAD

**Issue by ghost** [libSDL2pp/libSDL2pp#125]
Attempts to run `cmake .` in the top level of the repository results in a `Configuring incomplete, errors occurred!` message. Examination of the error log reveals that there's an attempt to use a command line option `-Wshorten-64-to-32`, which results in a `c++: error: unrecognized command line option '-Wshorten-64-to-32'` at which point cmake halts.

--Edit--
All SDL2 libraries and their appropriate development libraries are installed.

Software used:
VMware Workstation, Non-Commercial Edition version 14. Machine has 8 GB of memory, and 50 GB of storage.
Fedora Workstation 27 x86_64
gcc version 7.3.1
cmake 3.10.1

[CMakeError.log](https://github.com/libSDL2pp/libSDL2pp/files/1797997/CMakeError.log)
[CMakeOutput.log](https://github.com/libSDL2pp/libSDL2pp/files/1797998/CMakeOutput.log)

**Comment by AMDmi3** [comment]
Please show plain cmake output (e.g. `cmake . >log 2>&1`)

**Comment by AMDmi3** [comment]
Timeout
