### ISSUE TITLE
Error compiling example(and any other program)

### ISSUE THREAD

**Issue by shipof123** [libSDL2pp/libSDL2pp#127]
### When compiling i get the error:  
`/usr/local/include/SDL2pp/SDL.hh:25:24: fatal error: SDL_stdinc.h: No such file or directory`
### Running this command
`g++ -std=c++11 main.cpp lib = -L /usr/local/include/ -lSDL2pp`
### To compile the library I ran
`cmake . && make && make install`
### after running 

    g++ -std=c++11 main.cpp lib `sdl2-config --cflags` `sdl2-config --libs`
 
I get these errors
Usage: /usr/bin/sdl2-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs] [--static-libs]                                                        test.cpp:3:27: fatal error: SDL2pp/SDL2pp.h: No such file or directory                #include <SDL2pp/SDL2pp.h>

**Comment by shipof123** [comment]
using 

    g++ -std=c++11 main.cpp `sdl2-config --cflags` `sdl2-config --libs`
results in g++ not finding my  lib

**Comment by AMDmi3** [comment]
> `SDL2pp/SDL2pp.h`

This is not how the header is called.
I couldn't comprehend anything else at all.

**Comment by shipof123** [comment]
how do you include the header then?
