### ISSUE TITLE
Cant Compile SDL2PP

### ISSUE THREAD

**Issue by harshal-99** [libSDL2pp/libSDL2pp#128]
`harshal@harshal-PC ~/D/libSDL2pp-0.16.0> 

sudo cmake . && sudo  make && sudo  make install

-- Checking for -Wmissing-prototypes: yes
-- Checking for -Wtautological-compare: yes
-- Checking for -Wshorten-64-to-32: yes
-- Checking for experimental/optional header: no
-- libSDL2pp 0.16.0 standalone build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/harshal/Downloads/libSDL2pp-0.16.0
[  0%] Building CXX object CMakeFiles/SDL2pp.dir/SDL2pp/AudioDevice.cc.o
c++: error: unrecognized command-line option ‘-Wshorten-64-to-32’
make[2]: *** [CMakeFiles/SDL2pp.dir/build.make:83: CMakeFiles/SDL2pp.dir/SDL2pp/AudioDevice.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:261: CMakeFiles/SDL2pp.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
`
I have tried building using AUR and from Source either of them did not compile

**Comment by AMDmi3** [comment]
What compiler do you use? Also try version 0.16.1.

**Comment by harshal-99** [comment]
`harshal@harshal-PC ~> g++ --version g++ (GCC) 10.1.0


Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

Thanks man  0.16.1  Build Successed
