### ISSUE TITLE
how to compile with emscripten?

### ISSUE THREAD

**Issue by huison-cao** [libSDL2pp/libSDL2pp#133]
When I compile imgui, I have compiled sdl2 mixer, but when I compile sdl2pp, I still prompt that the package sdl2 mixer cannot be found:

**/vob/xgui/libSDL2pp$ emcmake cmake .**
configure: cmake . -DCMAKE_TOOLCHAIN_FILE=/vob/xgui/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/vob/xgui/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-threads
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  **Could NOT find SDL2_mixer (missing: SDL2_MIXER_LIBRARY)**
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL2_mixer.cmake:15 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:57 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/vob/xgui/libSDL2pp/CMakeFiles/CMakeOutput.log".
emcmake: error: 'cmake . -DCMAKE_TOOLCHAIN_FILE=/vob/xgui/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/vob/xgui/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-threads' failed (returned 1)

**Comment by huison-cao** [comment]
sidam@KONG:/vob/xgui/emsdk/upstream/emscripten/cache/ports$ ls
freetype      harfbuzz             ogg      sdl2        sdl2_image.zip  sdl2_mixer.0.2.zip  sdl2_net.zip  sdl2_ttf.zip  vorbis
freetype.zip  harfbuzz.2.0.tar.gz  ogg.zip  sdl2_image  **sdl2_mixer**      sdl2_net            sdl2_ttf      sdl2.zip      vorbis.zip
sidam@KONG:/vob/xgui/emsdk/upstream/emscripten/cache/ports$

**Comment by huison-cao** [comment]
emscripten is clang for webassembly. (https://emscripten.org)
Through webassembly, we can make the traditional compilation language run in the browser with high performance

**Comment by AMDmi3** [comment]
Well I know nothing about it, so you're on your own.
