### ISSUE TITLE
Examples UB: exception out of main

### ISSUE THREAD

**Issue by StarOrpheus** [libSDL2pp/libSDL2pp#134]
From cppreference about function-try-block: `Reaching the end of a catch clause for a function-try-block on a destructor also automatically rethrows the current exception as if by "throw;", but a return statement is allowed.`.
Exceptions out of main() is UB, so it would be nice to get rid of it in public examples.

Thanks for the lib nevertheless!

**Comment by StarOrpheus** [comment]
pr: https://github.com/libSDL2pp/libSDL2pp/pull/135

**Comment by ilyapopov** [comment]
As per your quote, rethrowing only happens on function-try-blocks for destructors, not for other functions. So use in the examples should be fine.

**Comment by AMDmi3** [comment]
I cannot see any UB here either, as function-try block is equivalent to plain try over the whole function body extended to member initializer list (which does not matter for `main`). The change is still good though, as we should avoid 'clever' or rare constructs in the examples. I'll review it tomorrow.

**Comment by StarOrpheus** [comment]
Sorry for the time spent, I've misread cppreference at late night. Definitely no UB, thanks.
