### ISSUE TITLE
Linking failed on macos

### ISSUE THREAD

**Issue by e7** [libSDL2pp/libSDL2pp#138]
I use vcpkg to install dependencies except libSDL2pp.

`mkdir build`
`cd build`
`cmake .. -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake`
works fine, but got error when `make` it.

> [  1%] Linking CXX shared library libSDL2pp.dylib
Undefined symbols for architecture x86_64:
  "_FT_Done_Face", referenced from:
      _TTF_CloseFont in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Done_FreeType", referenced from:
      _TTF_Quit in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Done_Glyph", referenced from:
      _Load_Glyph in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Get_Char_Index", referenced from:
      _get_char_index in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Get_Glyph", referenced from:
      _Load_Glyph in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Get_Kerning", referenced from:
      _TTF_Size_Internal in libSDL2_ttf.a(SDL_ttf.c.o)
      _TTF_GetFontKerningSize in libSDL2_ttf.a(SDL_ttf.c.o)
      _TTF_GetFontKerningSizeGlyphs32 in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Glyph_Stroke", referenced from:
      _Load_Glyph in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Glyph_To_Bitmap", referenced from:
      _Load_Glyph in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Init_FreeType", referenced from:
      _TTF_Init in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Library_Version", referenced from:
      _TTF_GetFreeTypeVersion in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Load_Glyph", referenced from:
      _Load_Glyph in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_MulFix", referenced from:
      _TTF_initFontMetrics in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Open_Face", referenced from:
      _TTF_OpenFontIndexDPIRW in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Outline_Transform", referenced from:
      _Load_Glyph in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Outline_Translate", referenced from:
      _Load_Glyph in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Render_Glyph", referenced from:
      _Load_Glyph in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Select_Size", referenced from:
      _TTF_SetFontSizeDPI in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Set_Char_Size", referenced from:
      _TTF_SetFontSizeDPI in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Set_Charmap", referenced from:
      _TTF_OpenFontIndexDPIRW in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Stroker_Done", referenced from:
      _Load_Glyph in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Stroker_New", referenced from:
      _Load_Glyph in libSDL2_ttf.a(SDL_ttf.c.o)
  "_FT_Stroker_Set", referenced from:
      _Load_Glyph in libSDL2_ttf.a(SDL_ttf.c.o)
  "_png_create_info_struct", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
      _IMG_SavePNG_RW_libpng in libSDL2_image.a(IMG_png.c.o)
  "_png_create_read_struct", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_create_write_struct", referenced from:
      _IMG_SavePNG_RW_libpng in libSDL2_image.a(IMG_png.c.o)
  "_png_destroy_read_struct", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_destroy_write_struct", referenced from:
      _IMG_SavePNG_RW_libpng in libSDL2_image.a(IMG_png.c.o)
  "_png_get_IHDR", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_get_PLTE", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_get_channels", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_get_io_ptr", referenced from:
      _png_read_data in libSDL2_image.a(IMG_png.c.o)
      _png_write_data in libSDL2_image.a(IMG_png.c.o)
  "_png_get_tRNS", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_get_valid", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_read_image", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_read_info", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_read_update_info", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_set_IHDR", referenced from:
      _IMG_SavePNG_RW_libpng in libSDL2_image.a(IMG_png.c.o)
  "_png_set_PLTE", referenced from:
      _IMG_SavePNG_RW_libpng in libSDL2_image.a(IMG_png.c.o)
  "_png_set_expand", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_set_gray_to_rgb", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_set_interlace_handling", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_set_longjmp_fn", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
      _IMG_SavePNG_RW_libpng in libSDL2_image.a(IMG_png.c.o)
  "_png_set_packing", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_set_read_fn", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_set_rows", referenced from:
      _IMG_SavePNG_RW_libpng in libSDL2_image.a(IMG_png.c.o)
  "_png_set_strip_16", referenced from:
      _IMG_LoadPNG_RW in libSDL2_image.a(IMG_png.c.o)
  "_png_set_tRNS", referenced from:
      _IMG_SavePNG_RW_libpng in libSDL2_image.a(IMG_png.c.o)
  "_png_set_write_fn", referenced from:
      _IMG_SavePNG_RW_libpng in libSDL2_image.a(IMG_png.c.o)
  "_png_write_png", referenced from:
      _IMG_SavePNG_RW_libpng in libSDL2_image.a(IMG_png.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libSDL2pp.8.3.0.dylib] Error 1
make[1]: *** [CMakeFiles/SDL2pp.dir/all] Error 2
make: *** [all] Error 2

**Comment by AMDmi3** [comment]
It looks like it's trying to link with static libraries instead of dynamic ones. This may happen if cmake cannot find dynamic libraries properly. However we should also switch to upstream cmake modules which SDL libraries ship with for some time already.

**Comment by AMDmi3** [comment]
Feedback timeout and probably fixed in 0.18.0.
