### ISSUE TITLE
Missing cmake file

### ISSUE THREAD

**Issue by durkisneer1** [libSDL2pp/libSDL2pp#140]
In the SDL2ppConfig.cmake file, the last line attempts to look for SDL2ppTargets.cmake under the same directory but it doesn't exist. This leads to an error saying "include could not find requested file". If I missed something in the installation walkthrough, let me know.

**Comment by AMDmi3** [comment]
Full build/install log please, some infor about your system and the list of contents of `${CMAKE_INSTALL_LIBDIR}/cmake/SDL2pp` after installation.
