### ISSUE TITLE
CMake error finding SDL_image

### ISSUE THREAD

**Issue by froart** [libSDL2pp/libSDL2pp#141]
Hello. when I cloned your repository and run "cmake ." as you mentioned in README, I get the following error: 

CMake Error at CMakeLists.txt:41 (find_package):
  By not providing "FindSDL2_image.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "SDL2_image", but CMake did not find one.

  Could not find a package configuration file provided by "SDL2_image" with
  any of the following names:

    SDL2_imageConfig.cmake
    sdl2_image-config.cmake

  Add the installation prefix of "SDL2_image" to CMAKE_PREFIX_PATH or set
  "SDL2_image_DIR" to a directory containing one of the above files.  If
  "SDL2_image" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

As far as I see in README SDL_image is an optional package. So what would resolve this issue?

**Comment by AMDmi3** [comment]
You need to disable `SDL2PP_WITH_IMAGE` (and probably bunch of other) option

**Comment by froart** [comment]
> You need to disable `SDL2PP_WITH_IMAGE` (and probably bunch of other) option

It worked, thank you. I commented out everything under  12 if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR) condition.

**Comment by AMDmi3** [comment]
You don't have to edit source for this. You can run e.g. `cmake -DSDL2PP_WITH_IMAGE=OFF .`, or tune options interactively with `ccmake` or `cmake-gui`. See cmake [docs](https://cmake.org/runningcmake/) for more info.

**Comment by froart** [comment]
> You don't have to edit source for this. You can run e.g. `cmake -DSDL2PP_WITH_IMAGE=OFF .`, or tune options interactively with `ccmake` or `cmake-gui`. See cmake [docs](https://cmake.org/runningcmake/) for more info.

Thanks for the tip. I am kinda new to cmake and it gives me headache, cause there's barely any decent tutorial, I can't understand the structure of it and where to put where to make things work, so I pick and choose.
