### ISSUE TITLE
Typo: GetGlyphMetrics doc comment describes ch as output parameter.

### ISSUE THREAD

**Issue by ilyapopov** [libSDL2pp/libSDL2pp#60]
See https://github.com/libSDL2pp/libSDL2pp/blob/master/SDL2pp/Font.hh#L459

**Comment by ooxi** [comment]
I don't get it, how does does documentation describe `ch` as an output parameter and which change would you suggest? The [TTF_GlyphMetrics](https://www.libsdl.org/projects/SDL_ttf/docs/SDL_ttf.html#SEC38) function describes `ch` as input.

**Comment by ilyapopov** [comment]
See #63

**Comment by ooxi** [comment]
Yes, you are right :+1: :)
