### ISSUE TITLE
Surface constructor parameters

### ISSUE THREAD

**Issue by ilyapopov** [libSDL2pp/libSDL2pp#62]
`flags` parameter is unused and should be set to zero. Do we need this parameter at all?

Mask parameters can take zero values meaning "default". Thus, the signature could be: 

    Surface::Surface(int width, int height, int depth, 
        Uint32 Rmask = 0, Uint32 Gmask = 0, Uint32 Bmask = 0, Uint32 Amask = 0);

Of course, I understand that changing the signature is a breaking change and not acceptable, thus an alternative overload can be added?

**Comment by AMDmi3** [comment]
I don't consider library API stable yet, so changing the function signature is not completely unacceptable. However I prefer to stick to upstream API, not only in a way that SDL2 code may be translated into SDL2pp in a straightforward manner, but also in a way that SDL2pp code should be readable to a person with SDL2 experience only, so I'd prefer not to change arguments order and not to remove arguments not at the end of the list.

With this specific function it's not even possible: all arguments are integers, so overload would be ambiguous in most cases:

```
#include <stdint.h>
#include <iostream>

typedef uint32_t Uint32;

class Test {
public:
    void Foo(int flags, int width, int height, int depth, Uint32 Rmask = 0, Uint32 Gmask = 0, Uint32 Bmask = 0, Uint32 Amask = 0) {
        std::cerr << "foo with flags\n";
    }

    void Foo(int width, int height, int depth, Uint32 Rmask = 0, Uint32 Gmask = 0, Uint32 Bmask = 0, Uint32 Amask = 0) {
        std::cerr << "foo without flags\n";
    }
};

int main() {
    Test t;
    t.Foo(0, 32, 32, 32, 0xff, 0xff00, 0xff0000);
    t.Foo(32, 32, 32, 0xff, 0xff00, 0xff0000);
    return 0;
}
```

```
% c++ 1.cc && ./a.out 
foo with flags
foo with flags
```

I'm quite surprised it compiles.

**Comment by ilyapopov** [comment]
But now in SDL2pp mask parameters dot't even have defaults. See https://github.com/libSDL2pp/libSDL2pp/blob/master/SDL2pp/Surface.hh#L190

**Comment by AMDmi3** [comment]
Oh, true. But other arguments still apply.
