### ISSUE TITLE
SDL_GetWindowSurface / SDL_gfx

### ISSUE THREAD

**Issue by ooxi** [libSDL2pp/libSDL2pp#65]
Would a patch for getting `SDL2pp::Surface` from `SDL2pp::Window` be accepted, or was this method left out in order to not encourage legacy code?

On a related note, would you think about adding SDL_gfx support? Or are you aware of a better suited library using `SDL_Renderer` instead of `SDL_Surface`?

**Comment by ooxi** [comment]
Ok it looks like the documentation is outdated. SDL2_gfx does in fact use `SDL_Renderer` instead of `SDL_Surface` everywhere. Therefore I do not need `SDL_Surface` and thus no `SDL_GetWindowSurface` wrapper :)

I would nevertheless provide one if you would accept the patch.

**Comment by AMDmi3** [comment]
I'd prefer to not touch this function as it breaks encapsulation and consistency.
- surface returned by SDL_GetWindowSurface may not be freed
- surface is invalidated on window resize
