### ISSUE TITLE
Use std::runtime_error instead of std::exception

### ISSUE THREAD

**Issue by Alicemargatroid** [libSDL2pp/libSDL2pp#68]
I've noticed that Exception.hh uses std::exception rather than std::runtime_error; on many platforms, the compiler will attempt to make sure std::runtime_error will be able to allocate memory for the exception string even in the face of a complete exhaustion of memory (GCC tries really hard, MSVC tries pretty hard, Clang doesn't care, as of 2014).

Might it be possible to use std::runtime_error instead of keeping the std::strings inside of SDL2pp::Exception? Would be very helpful on memory bound platforms.

**Comment by AMDmi3** [comment]
I don't really believe in such an optimization, as when you don't have heap space for a couple of strings, you probably are screwed anyway. There *is* a point for SDL2pp::Exception to be derived from std::runtime_error though, as it's indeed a kind of runtime error.

Unfortunately, additional member strings can't be dropped from SDL2pp::Exception: ```SDL_GetError()``` which it relies on returns pointer to buffer which is dynamically changed (and not a pointer to static string which may be safely stored as is), so exception must save a copy of error string. Function name may be turned into a pointer though, but I'd prefer not to do it for the sake of consistency, extensibility (may need ```Exception::Exception(const std::string&)``` later) and seeming meaninglessness explained above.

Please see issue-68 branch - it makes Exception derived from std::runtime_error and optimizes what() string construction a bit. I don't see what more can be done here.

**Comment by Alicemargatroid** [comment]
@AMDmi3 I was mostly thinking embedded devices, as I hit a snag with Raspberry Pi, but I agree that your commit is more than sufficient to reduce the likelihood of problems as far as they can reasonably go, without reducing functionality.
