### ISSUE TITLE
Data encapsulation is broken in some classes

### ISSUE THREAD

**Issue by Gumichan01** [libSDL2pp/libSDL2pp#74]
In **Renderer**, **Window** and **Surface**, the definition of the member function *Get()* breaks encapsulation because the user can get an SDL\_Renderer of a specific SDL\_Window just calling **Get()** from the Renderer or the Window. 

Example:

    Window window("libSDL2pp demo: sprites", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, SDL_WINDOW_RESIZABLE);
    Renderer render(window, -1, SDL_RENDERER_ACCELERATED);
    Surface surf(TESTDATA_DIR "/test.png");

    SDL_Renderer *r1 = render.get();                      // Encapsulation issue !!!!
    SDL_Renderer *r2 = SDL_GetRenderer(window.get());     // Encapsulation issue again !!!!
    // (r1 == r2) normally
    // Do anything you want with that ...

This data encapsulation issue should be severe with **Surface** objects, as you can see in this piece of code:

    SDL_Surface * s = surf.get();
    // s can be modified outside of Surface, broken encapsulation
    Texture sprite(render, surf);

Moreover, some of these getters seem to be only used for internal needs (texture/renderer creation).
So, a possible solution in this case should be using friendship in order to restrict the access of internal fields.
Hence, these getters will become useless, and then we will have **Texture** as a friend class of **Surface** and **Renderer** as a a friend of **Window**.
In the other case, that is to say with getter that are not internally used, remove them seems to be a good idea.

Well, it is just a suggestion. Maybe you need that for debugging or perhaps for any good reasons. If you have some examples of code that justify the use of one of these getters from external programs, I will be glad to know.

**Comment by ooxi** [comment]
I think the reason behind allowing `get` is having SDL plugins not yet supported by libSDL2pp which need the SDL C structures.

**Comment by AMDmi3** [comment]
This is intentional and needed for interoperation with C-style SDL2 code.
