### ISSUE TITLE
Texture::Update should support rvalues

### ISSUE THREAD

**Issue by exap** [libSDL2pp/libSDL2pp#77]
At the moment there is the function

> Texture& Texture::Update(const Optional<Rect>& rect, Surface&& surface)

It should be possible to pass the `surface` as a rvalue as I don't see any counterargument.

**Comment by AMDmi3** [comment]
You're right. ```Update()``` does not take ```const Surface&``` because surface locking is non-const operation (this may be revisited; though constness is hard to handle properly with SDL plain C API). But yes, no problem to add ```Update(Surface&&)```. Will do.

**Comment by AMDmi3** [comment]
Fixed in 0.13.0
