### ISSUE TITLE
SDL_SetWindowResizable() support

### ISSUE THREAD

**Issue by AMDmi3** [libSDL2pp/libSDL2pp#83]

**Comment by Kiritow** [comment]
Hello. I am writing a wrapper of SDL2 too. My program can't start when SDL_SetWindowResizable() is called. Is this a bug of SDL2?

**Comment by AMDmi3** [comment]
> My program can't start when SDL_SetWindowResizable() is called

Works fine for me. It's a bad idea to call it in general though, because there are tiled WMs on which limiting window resize operations will never work properly.
