### ISSUE TITLE
Exception dll-interface issues in MSVS

### ISSUE THREAD

**Issue by Artalus** [libSDL2pp/libSDL2pp#87]
When compiling library in Visual Studio 2015 / 2017 RC and using it in project I get lots of warnings of these two types:

`Warning C4251: 'SDL2pp::Mixer::current_music_hook_': class 'std::unique_ptr<SDL2pp::Mixer::MusicHook,std::default_delete<_Ty>>' needs to have dll-interface to be used by clients of class 'SDL2pp::Mixer'`

`Warning C4275: non dll-interface class 'std::runtime_error' used as base for dll-interface class 'SDL2pp::Exception'`

From [what I've googled](http://stackoverflow.com/questions/24511376/how-to-dllexport-a-class-derived-from-stdruntime-error), MSVS got some problems with exporting STL types.

Also - is it possible to compile libSDL2pp as static lib? I've managed to get rid of those warnings by #defining `SDL2PP_STATIC_DEFINE` project-wise, but as it still uses .dll, I'm really not sure if it is a way to go.

**Comment by AMDmi3** [comment]
Bundled SDL2pp build builds static library, doesn't that work for you? Regarding the warning, as I understand it can be ignored.

**Comment by Artalus** [comment]
Bundling is described for CMake - does the same rules apply to adding whole SDL2pp sources to VS project and building it as part of my program? I will try it once I get some free time, but in my opinion it'd still be a useful feature to be able to build SDL2pp statically.

**Comment by AMDmi3** [comment]
> Bundling is described for CMake - does the same rules apply to adding whole SDL2pp sources to VS project and building it as part of my program?

When you add the source to your project there are no rules - you are free to build it any way you want. Actually, in this case you don't even need to generate any kind of library, just the usual object files. That should work fine, but you'll have to create ```Export.hh``` (which is normally generated by CMake) yourself, with the following contents:

```
#pragma once
#define SDL2PP_EXPORT
```

> but in my opinion it'd still be a useful feature to be able to build SDL2pp statically

Again, there is such feature - it's built statically when bundled. May add a flag to build it statically when not bundled as well.
