### ISSUE TITLE
SDL2pp include path for SDL2 doesn't follow SDL2 conventions

### ISSUE THREAD

**Issue by zub2** [libSDL2pp/libSDL2pp#88]
SDL2pp assumes it can find SDL.h (and "sibling" headers) via `#include <SDL2/SDL.h>`.

This goes against the expectations of SDL2, as can be seen e.g. by running `pkg-config --cflags-only-I sdl2` or looking at any (or at least most) SDL2 tutorials. These expect to use just `#include <SDL.h>`.

This doesn't matter much of the time (with the exception that application code using SDL2pp needs to either follow SDL2pp's convention or add the foo/SDL2 include paths on their own). But it causes real issues when the SDL2_* helper libs (image, ttf, mixer) are installed into directories other than where the SDL2 itself is installed. This is because e.g. SDL2_image.h includes SDL2 headers like this:

> #include "SDL.h"
> #include "SDL_version.h"
> #include "begin_code.h"

This works if either the $SDL2_INSTALL/include/SDL2 directory is in the include path or if the SDL2_image.h is installed in the same directory as the SDL2 headers are. But if this is not the case the #includes for SDL2 in SDL_image are not resolved. Same thing happens for SDL2_ttf and SDL2_mixer.

It is possible to work around this issue by adding -DCMAKE_INCLUDE_PATH=... argument which adds the foo/SDL2 paths from the outside, but this is neither nice nor intuitive.

**Comment by AMDmi3** [comment]
As I've stated before, SDL include conventions are broken. We have two versions of SDL library, additionally we have wrappers like SDL2pp which may use similarly named files (such as SDL.h; luckily SDL2pp uses SDL.hh), so all these conflict. To avoid filesystem conflicts, includes from different libs are thoughtfully installed into dedicated subdirectories. Now, SDL conventions just ignore that and use unprefixed includes asking for problems with wrappers or when SDL and SDL2 apps are used in the same project. I'd prefer to not follow this, but it seems I'll have to after all.

In progress.

**Comment by AMDmi3** [comment]
Please check out sdl2-include-paths branch

**Comment by zub2** [comment]
I can confirm sdl2-include-paths works for me. Thanks! Do you plan to integrate this into further releases?

Btw. I agree with your #include reasoning but that fact that SDL2_image and friends would be unusable then is the stronger factor for me.

**Comment by AMDmi3** [comment]
> Thanks! Do you plan to integrate this into further releases?

Sure, I've merged it to master. I'll ship a new release after sorting out #89.

> Btw. I agree with your #include reasoning but that fact that SDL2_image and friends would be unusable then is the stronger factor for me

Same here
