### ISSUE TITLE
Please add an option to choose between static and shared build

### ISSUE THREAD

**Issue by zub2** [libSDL2pp/libSDL2pp#89]
If I understand the CMakeLists.txt correctly, SDL2pp always builds shared library when stand-alone build is done and always builds static library if the CMakeLists.txt is used from another project.

Could you please add a CMake option option that allows to override this?

**Comment by AMDmi3** [comment]
On it. Out of curiosity, do you want static library for standalone build, or shared library for bundled build, or both? Do you need both shared and static libs at the same time?

**Comment by zub2** [comment]
I need standalone static build. I think shared for bundled build can be useful too (probably more useful than standalone static). Supporting both at once is the most general way and perhaps can be useful but I don't think it's needed often.

I'm actually using SDL2pp in a CMake project, so ideally I should be able to just use the "bundled" mode. But I'm also building SDL itself from CMake via ExternalProject. So I can't let SDL2pp use find_path/find_library to find SDL as there's no SDL at configuration time.
