### ISSUE TITLE
Please add ctors w/o arguments for classes where this makes sense

### ISSUE THREAD

**Issue by zub2** [libSDL2pp/libSDL2pp#90]
Many classes in SDL2pp just wrap an underlying SDL pointer (e.g. Window - SDL_Window*, Surface - SDL_Surface*, Texture - SDL_Texture*). But unlike the original type (e.g. SDL_Texture*), it's not possible to create a "null" SDL2pp::Texture instance because it does not have a ctor w/o arguments. I could use SDL2pp::Texture::Texture(SDL_Texture*) and give it nullptr, but I'm not sure this is what the ctor is intended for. Furthermore it's not possible to test if the stored pointer is null.

I understand not allowing invalid (containg a nullptr) instances of these classes gives them some nice properties but it also makes them difficult to use. Consider e.g. a member variable for a texture that is lazy-loaded. If the type of the member is SDL2pp::Texture then I need to initialize it already in the class' ctor's initializer list. Or I need to use a pointer (e.g std::unique_ptr&lt;SDL2pp::Texture&gt;) or optional (e.g. boost::optional&lt;SDL2pp::Texture&gt;). Had I used SDL_Texture* instead, I could initialize it to nullptr and then load the texture later.

I think that for classes that just wrap a pointer to a SDL type, it would make sense to add a ctor w/o argument that initializes the internal pointer to nullptr and an explicit operator bool() to test the validity of the object. Then one could write things like:

    struct Foo
    {
        SDL2pp::Texture texture;
        void bar()
        {
            if (!texure)
                texture = SDL2pp::Texture(renderer, surface);
            //...
        }
    }

But this might also require some changes in methods of the wrapping classes: extra checks of the contained pointer. Or, you can define that they must not be called if the object is not valid (contains a nullptr).

**Comment by zub2** [comment]
Ouch... It *is* possible to check if the stored pointer is null via Get(). So maybe using ctor with nullptr + using Get() is OK?

Nevertheless, adding ctor w/o arguments and explicit operator bool() would make the classes easier to use I think.

**Comment by ooxi** [comment]
Wouldn't it be better to use [`std::optional<SDL2pp::Texture>`](http://en.cppreference.com/w/cpp/utility/optional) instead of a `SDL2pp::Texture` initialized with `nullptr`, given your problem description?

**Comment by AMDmi3** [comment]
No, this is extremely bad design choice. If there is Texture object, there must be a texture. The only exception I can allow is moved-from object. If you need nullable object, you should use unique_ptr or optional.

**Comment by zub2** [comment]
I think it boils down to this: is a SDL2pp::Texture a texture, or some sort of handle/pointer to a texture?

In the current view it is treated as a texture and opening the doors to nullptr textures means in all places where a Texture is needed one would have to check if it's indeed valid. I agree this is ugly.

On the other hand, the wrapped object is a SDL_Texture*, nothing more. And I find it strange if I have to use a pointer to allocate a pointer. It's an extra memory allocation and indirection on use. Optional is less bad, but still it brings in an extra bool.

I would like to have an abstraction that would give me the benefits of C++ without adding extra overhead. One way I could think of is creating a "SDL unique pointer" that would handle the move semantics + destruction and that would provide operator-> (and maybe operator*) that return a temporary that lets me do the actual calls. This way, the SDL objects would be pointers (well, e.g. `SDLUniquePtr<SDL_Texture> texture;`), as they are in C, but I could do e.g. `texture->SetAlphaMod(128);`.

With some more C++ magic it could even be that both unique pointer and shared pointer-like templates are supported.

But this would be a big change.

Also: If e.g. Texture is not a pointer/handle to SDL_Texture, I think it's ctor should not accept nullptr.

**Comment by AMDmi3** [comment]
> I think it boils down to this: is a SDL2pp::Texture a texture, or some sort of handle/pointer to a texture?

Definitely a texture.

> On the other hand, the wrapped object is a SDL_Texture*, nothing more. And I find it strange if I have to use a pointer to allocate a pointer. It's an extra memory allocation and indirection on use. Optional is less bad, but still it brings in an extra bool.

Yes, but I don't think that's an overhead a sane person should care about.

> If e.g. Texture is not a pointer/handle to SDL_Texture, I think its ctor should not accept nullptr.

I've added corresponding ```assert()```s yesterday.

**Comment by AMDmi3** [comment]
Otoh I think it'd be even better to replace asserts with nullptr check + throw invalid_argument and explicitly disabling a nullptr_t constructor.
