### ISSUE TITLE
Please mark ctors from SDL raw pointers explicit

### ISSUE THREAD

**Issue by zub2** [libSDL2pp/libSDL2pp#91]
Currently ctors for the raw SDL pointers, e.g. SDL2pp::Texture::Texture(SDL_Texture*) or SDL2pp::Surface::Surface(SDL_Surface*) are not explicit. This is dangerous because the ctor takes ownership of the raw pointer. Conside the following example:

	void foo(const SDL2pp::Surface& surface)
	{
		// ...
	}

	void bar()
	{
		SDL_Surface *rawSurface = SDL_CreateRGBSurface(0, 64, 64, 32, 8, 8, 8, 8);
		if (rawSurface)
		{
			foo(rawSurface);
			// the call above created a temporary SDL2pp::Surface that took ownership
			// of the rawSurface and then destroyed it so the rawSurface is no longer
			// valid
			SDL_FreeSurface(rawSurface);
		}
	}

Making such ctor explicit means the programmer has to explicitly write the ctor call if (s)he wants to pass the ownership.

This is semantically similar to unique_ptr's ctor from raw pointer which is also explicit - for similar reason I think.

**Comment by ooxi** [comment]
I'm by far not an expert in C++ but I agree with zub2: everything which transfers ownership should be explicit.
