### ISSUE TITLE
(bug) CustomRWops also needs to define size()

### ISSUE THREAD

**Issue by hsdk123** [libSDL2pp/libSDL2pp#94]
I've been trying to use CustomRWops with SDL_ttf, and I'd been getting continuous crashes about a nullpointer dereferencing. After some looking into things, it seems the reason is that CustomRWops also needs to define size().

Otherwise, it crashes on this line within SDL_ttf.h
```
stream->size = (unsigned long)(SDL_RWsize(src) - position);
```
SDL_RWsize is a macro for the size function, which is currently non-existent for CustomRWop, causing the null pointer dereference error.

This seems like a rather big bug that needs a small update.

**Comment by AMDmi3** [comment]
On it. Not sure why I've missed it.

**Comment by AMDmi3** [comment]
Fixed, thank you!

**Comment by hsdk123** [comment]
I've checked things work on my side as well. You are absolutely the most fastest person in dealing with issues that I've ever met on Github. Thank you!

**Comment by AMDmi3** [comment]
Thank you! Unfortunately that's not always the case :grin:
