### ISSUE TITLE
Android makefile, ios project

### ISSUE THREAD

**Issue by hsdk123** [libSDL2pp/libSDL2pp#95]
Hi, I'm currently facing a few difficulties trying to get libSDL2pp to build for android and ios - if a working android makefile and ios workspace happen to be up, they would be of great convenience.

**Comment by AMDmi3** [comment]
libSDL2pp uses CMake build system, which is capable of generating project files or makefiles for various environments, see documentation for CMake and/or for your build environments/IDEs. Some relevant links I've been able to find:

https://developer.android.com/ndk/guides/cmake.html
https://cmake.org/cmake/help/v3.8/generator/Xcode.html

**Comment by hsdk123** [comment]
@AMDmi3 Thanks, I've realised trying to get cmake to work with the android ndk was way too fussy, and I've instead gone the route of just adding libsdl2pp in my source files instead of building it as a library. I've had to remove all insertions of SDL2PP_EXPORT and create a custom Config.hh so that things bind together. Otherwise this seems to work without problem. 

I'll see how I take things with ios and post some results - might be useful for future reference.

**Comment by AMDmi3** [comment]
Interesting, thank you!

**Comment by pvallet** [comment]
Hello, I'm also trying to build under android. I have managed to build a small project using gradle + CMake (I have a hello world on my github page if you're interested) and I use SDL2pp as a submodule.

However, when my CMakeLists.txt call the one that SDL2pp, the module that finds SDL2 tries to find SDLmain, which is not built by the android makefile. As I already define SDL2_INCLUDE_DIR and such variables, I just commented the line FIND_PACKAGE(SDL2).

It would be nice to have a CMake option to bypass this line without modifying SDL2pp source.

**Comment by AMDmi3** [comment]
Perhaps it should just never look for SDLmain on Android? Is there a way to check whether this is an sndroid build in CMake?

**Comment by pvallet** [comment]
Yes, under cmake you can check if you are on android with if(ANDROID).

However, it won't solve the problem as it is CMakeLists.txt from SDL2pp that calls FIND_PACKAGE(SDL2), and SDLmain is needed here (in FindSDL2.cmake).

I think the cleanest way would be to allow bypassing FIND_PACKAGE(SDL2) with a CMake switch, as people might want to look for SDL2 themselves.

**Comment by AMDmi3** [comment]
Then I do not understand the problem. You say that there's no SDLmain, but it's still needed. And you cannot bypass FIND_PACKAGE(SDL2) in SDL2pp because SDL2pp needs it.

**Comment by pvallet** [comment]
Yes I do understand that SDL2pp needs it, but as its implementation of Findpackage(SDL) is not suitable for android, I wrote my own, and therefore I need to bypass the one from SDL2pp
